---
tenants:
  - name: S1_FABRIC
    mac_vrf_vni_base: 10000
    vrfs:
      - name: OVERLAY
        vrf_vni: 10
        svis:
          - id: 10
            name: 'Ten'
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          - id: 20
            name: 'Twenty'
            enabled: true
            ip_address_virtual: 10.20.20.1/24
          - id: 25
            name: 'Twenty-five'
            tags: [ "Wifi" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.25.25.1
            nodes:
              - node: s1-spine1
                ip_address: 10.25.25.2/24
              - node: s1-spine2
                ip_address: 10.25.25.3/24
